
import Button from '@/app/components/Button';
import React from 'react';

export const metadata = {
	title: "Mission | About",
	description: "Generated by create next app",
};

const Mission = () => {
    return (
		<main className='mt-10'>
            <div>Mission page</div>
            <Button></Button>
		</main>
	);
};

export default Mission;