import React from 'react';

export const metadata = {
	title: "About",
	description: "Generated by create next app",
};

const About = () => {
    // throw new Error("There is a huge error!");
    
    return (
		<main className='mt-10'>
			<div>About us page</div>
		</main>
	);
};

export default About;