import { Poppins } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const poppins = Poppins({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='p-6'>
          <body className={poppins.className}>
              <nav>
                  <ul className='flex gap-6'>
                      <li className=''>
                          <Link href="/">Home</Link>
                      </li>
                      <li>
                          <Link href="/about">About</Link>
                      </li>
                      <li>
                          <Link href="/blogs">Blogs</Link>
                      </li>
                      <li>
                          <Link href="/posts">Posts</Link>
                      </li>
                  </ul>
              </nav>
              <hr></hr>
              {children}</body>
    </html>
  )
}
